import { BankPreset } from '../types';

export const PHILIPPINE_BANKS: BankPreset[] = [
  // DIGITAL BANKS
  {
    code: 'GOTYME',
    name: 'GoTyme Bank',
    shortName: 'GoTyme',
    category: 'digital',
    primaryColor: '#00D1C1',
    gradient: 'from-[#004B49] via-[#008F87] to-[#00D1C1]',
    textColor: '#FFFFFF',
    iconBg: '#002E2D',
    logoEmoji: '🩵',
    tagline: 'Up to 5.0% p.a. • Go Rewards',
    interestRate: '4.0% - 5.0% p.a.',
  },
  {
    code: 'SEABANK',
    name: 'SeaBank Philippines',
    shortName: 'SeaBank',
    category: 'digital',
    primaryColor: '#FF5722',
    gradient: 'from-[#C4380E] via-[#E84E1B] to-[#FF7043]',
    textColor: '#FFFFFF',
    iconBg: '#4A1405',
    logoEmoji: '🟠',
    tagline: 'Daily Interest Credit • Free Transfers',
    interestRate: '4.5% p.a.',
  },
  {
    code: 'MAYA_BANK',
    name: 'Maya Bank',
    shortName: 'Maya Bank',
    category: 'digital',
    primaryColor: '#00D632',
    gradient: 'from-[#0A1F0D] via-[#0F3818] to-[#00D632]',
    textColor: '#FFFFFF',
    iconBg: '#051408',
    logoEmoji: '💚',
    tagline: 'Up to 14.0% p.a. High Yield Savings',
    interestRate: '3.5% - 14.0% p.a.',
  },
  {
    code: 'TONIK',
    name: 'Tonik Digital Bank',
    shortName: 'Tonik',
    category: 'digital',
    primaryColor: '#7B1FA2',
    gradient: 'from-[#38006B] via-[#6A1B9A] to-[#AB47BC]',
    textColor: '#FFFFFF',
    iconBg: '#210042',
    logoEmoji: '💜',
    tagline: 'Up to 6.0% Time Deposit Stashes',
    interestRate: '4.0% - 6.0% p.a.',
  },
  {
    code: 'CIMB',
    name: 'CIMB Bank Philippines',
    shortName: 'CIMB',
    category: 'digital',
    primaryColor: '#ED1B24',
    gradient: 'from-[#7F0000] via-[#C62828] to-[#ED1B24]',
    textColor: '#FFFFFF',
    iconBg: '#3F0000',
    logoEmoji: '🔴',
    tagline: 'GSave & UpSave Account',
    interestRate: '2.5% - 12.0% p.a.',
  },
  {
    code: 'UNOBANK',
    name: 'UNObank',
    shortName: 'UNObank',
    category: 'digital',
    primaryColor: '#F57C00',
    gradient: 'from-[#4E1D00] via-[#8C3A00] to-[#FF9800]',
    textColor: '#FFFFFF',
    iconBg: '#2E1000',
    logoEmoji: '🟡',
    tagline: 'Smart Savings with UNO Boost',
    interestRate: '4.25% - 6.5% p.a.',
  },
  {
    code: 'OWNBANK',
    name: 'OwnBank',
    shortName: 'OwnBank',
    category: 'digital',
    primaryColor: '#FBBF24',
    gradient: 'from-[#451A03] via-[#78350F] to-[#D97706]',
    textColor: '#FFFFFF',
    iconBg: '#260D02',
    logoEmoji: '🪙',
    tagline: 'High interest time deposit up to 7.5%',
    interestRate: '6.0% - 7.5% p.a.',
  },
  {
    code: 'DISKARTECH',
    name: 'DiskarTech (RCBC)',
    shortName: 'DiskarTech',
    category: 'digital',
    primaryColor: '#00BCD4',
    gradient: 'from-[#00363A] via-[#006064] to-[#00ACC1]',
    textColor: '#FFFFFF',
    iconBg: '#001E20',
    logoEmoji: '🩵',
    tagline: 'Digital banking by RCBC with 6.5% interest',
    interestRate: '6.5% p.a.',
  },
  {
    code: 'KOMO',
    name: 'Komo (EastWest)',
    shortName: 'Komo',
    category: 'digital',
    primaryColor: '#3F51B5',
    gradient: 'from-[#1A237E] via-[#283593] to-[#5C6BC0]',
    textColor: '#FFFFFF',
    iconBg: '#0D123F',
    logoEmoji: '💙',
    tagline: 'Digital banking backed by EastWest Bank',
    interestRate: '2.5% p.a.',
  },

  // COMMERCIAL & TRADITIONAL BANKS
  {
    code: 'BDO',
    name: 'BDO Unibank',
    shortName: 'BDO',
    category: 'commercial',
    primaryColor: '#0038A8',
    gradient: 'from-[#001845] via-[#002878] to-[#0050C8]',
    textColor: '#FFFFFF',
    iconBg: '#001030',
    logoEmoji: '🏦',
    tagline: 'We find ways',
  },
  {
    code: 'BPI',
    name: 'Bank of the Philippine Islands',
    shortName: 'BPI',
    category: 'commercial',
    primaryColor: '#B71C1C',
    gradient: 'from-[#4A0000] via-[#850D0D] to-[#B71C1C]',
    textColor: '#FFFFFF',
    iconBg: '#2A0000',
    logoEmoji: '🏛️',
    tagline: 'Ready today. Ready tomorrow.',
  },
  {
    code: 'UNIONBANK',
    name: 'UnionBank of the Philippines',
    shortName: 'UnionBank',
    category: 'commercial',
    primaryColor: '#FF6D00',
    gradient: 'from-[#3E1A00] via-[#B24A00] to-[#FF6D00]',
    textColor: '#FFFFFF',
    iconBg: '#240F00',
    logoEmoji: '🟧',
    tagline: 'Power to the Filipino tech forward bank',
  },
  {
    code: 'METROBANK',
    name: 'Metrobank',
    shortName: 'Metrobank',
    category: 'commercial',
    primaryColor: '#0D47A1',
    gradient: 'from-[#001064] via-[#012E8A] to-[#1565C0]',
    textColor: '#FFFFFF',
    iconBg: '#000A38',
    logoEmoji: '🏢',
    tagline: 'You\'re in good hands',
  },
  {
    code: 'SECURITY_BANK',
    name: 'Security Bank',
    shortName: 'Security Bank',
    category: 'commercial',
    primaryColor: '#00838F',
    gradient: 'from-[#002C33] via-[#005763] to-[#00838F]',
    textColor: '#FFFFFF',
    iconBg: '#001A1E',
    logoEmoji: '🛡️',
    tagline: 'BetterBanking is our pledge',
  },
  {
    code: 'RCBC',
    name: 'Rizal Commercial Banking Corp',
    shortName: 'RCBC',
    category: 'commercial',
    primaryColor: '#0277BD',
    gradient: 'from-[#002F4D] via-[#01579B] to-[#0288D1]',
    textColor: '#FFFFFF',
    iconBg: '#001B2E',
    logoEmoji: '🌊',
    tagline: 'Partners Through Generations',
  },
  {
    code: 'LANDBANK',
    name: 'Land Bank of the Philippines',
    shortName: 'Landbank',
    category: 'commercial',
    primaryColor: '#2E7D32',
    gradient: 'from-[#0E3813] via-[#1B5E20] to-[#388E3C]',
    textColor: '#FFFFFF',
    iconBg: '#09210C',
    logoEmoji: '🌾',
    tagline: 'Serving the nation and agriculture',
  },
  {
    code: 'PNB',
    name: 'Philippine National Bank',
    shortName: 'PNB',
    category: 'commercial',
    primaryColor: '#005696',
    gradient: 'from-[#001D38] via-[#003B6B] to-[#0069B4]',
    textColor: '#FFFFFF',
    iconBg: '#001021',
    logoEmoji: '🇵🇭',
    tagline: 'You First',
  },
  {
    code: 'CHINABANK',
    name: 'China Banking Corporation',
    shortName: 'Chinabank',
    category: 'commercial',
    primaryColor: '#880E4F',
    gradient: 'from-[#380020] via-[#5C0634] to-[#AD1457]',
    textColor: '#FFFFFF',
    iconBg: '#210013',
    logoEmoji: '🧧',
    tagline: 'Your success is our business',
  },
  {
    code: 'EASTWEST',
    name: 'EastWest Bank',
    shortName: 'EastWest',
    category: 'commercial',
    primaryColor: '#6A1B9A',
    gradient: 'from-[#2A0845] via-[#4A148C] to-[#7B1FA2]',
    textColor: '#FFFFFF',
    iconBg: '#1A042E',
    logoEmoji: '🧭',
    tagline: 'Your bridge to growth',
  },
  {
    code: 'PSBANK',
    name: 'Philippine Savings Bank',
    shortName: 'PSBank',
    category: 'commercial',
    primaryColor: '#00695C',
    gradient: 'from-[#00251F] via-[#004D40] to-[#00796B]',
    textColor: '#FFFFFF',
    iconBg: '#001411',
    logoEmoji: '💰',
    tagline: 'Simple lang. Maaasahan.',
  },
  {
    code: 'DBP',
    name: 'Development Bank of the Philippines',
    shortName: 'DBP',
    category: 'commercial',
    primaryColor: '#1565C0',
    gradient: 'from-[#072448] via-[#0B3C73] to-[#1E88E5]',
    textColor: '#FFFFFF',
    iconBg: '#04162C',
    logoEmoji: '🏗️',
    tagline: 'Building a stronger future for the country',
  },

  // E-WALLETS
  {
    code: 'GCASH',
    name: 'GCash',
    shortName: 'GCash',
    category: 'ewallet',
    primaryColor: '#0070BA',
    gradient: 'from-[#002F6C] via-[#0055A5] to-[#007DFE]',
    textColor: '#FFFFFF',
    iconBg: '#001C42',
    logoEmoji: '💙',
    tagline: 'Ang wallet ng bawat Pilipino',
  },
  {
    code: 'MAYA_WALLET',
    name: 'Maya E-Wallet',
    shortName: 'Maya',
    category: 'ewallet',
    primaryColor: '#00D632',
    gradient: 'from-[#051C09] via-[#0D4419] to-[#00D632]',
    textColor: '#FFFFFF',
    iconBg: '#030E05',
    logoEmoji: '💚',
    tagline: 'Everything and a bank',
  },
  {
    code: 'GRABPAY',
    name: 'GrabPay Philippines',
    shortName: 'GrabPay',
    category: 'ewallet',
    primaryColor: '#00B14F',
    gradient: 'from-[#003819] via-[#006E31] to-[#00B14F]',
    textColor: '#FFFFFF',
    iconBg: '#00210E',
    logoEmoji: '🟢',
    tagline: 'Food, Rides & Cashless Payments',
  },
  {
    code: 'SHOPEEPAY',
    name: 'ShopeePay',
    shortName: 'ShopeePay',
    category: 'ewallet',
    primaryColor: '#EE4D2D',
    gradient: 'from-[#4D1206] via-[#942710] to-[#EE4D2D]',
    textColor: '#FFFFFF',
    iconBg: '#2B0A03',
    logoEmoji: '🧡',
    tagline: 'Deals, Cashback & Shopping Wallet',
  },
  {
    code: 'COINSPH',
    name: 'Coins.ph',
    shortName: 'Coins.ph',
    category: 'ewallet',
    primaryColor: '#F5A623',
    gradient: 'from-[#3D2600] via-[#7A4C00] to-[#F5A623]',
    textColor: '#FFFFFF',
    iconBg: '#211500',
    logoEmoji: '🪙',
    tagline: 'Crypto & Everyday Digital Wallet',
  },
  {
    code: 'PALAWANPAY',
    name: 'PalawanPay',
    shortName: 'PalawanPay',
    category: 'ewallet',
    primaryColor: '#FBC02D',
    gradient: 'from-[#382B00] via-[#664F00] to-[#FBC02D]',
    textColor: '#FFFFFF',
    iconBg: '#211900',
    logoEmoji: '🌴',
    tagline: 'Padala at Mabilisang Bayad',
  },

  // CASH ON HAND
  {
    code: 'CASH',
    name: 'Physical Cash / Wallet',
    shortName: 'Cash',
    category: 'cash',
    primaryColor: '#10B981',
    gradient: 'from-[#064E3B] via-[#065F46] to-[#10B981]',
    textColor: '#FFFFFF',
    iconBg: '#022C22',
    logoEmoji: '💵',
    tagline: 'Bills & Coins on hand',
  },
];

export const getBankByCode = (code: string): BankPreset => {
  const found = PHILIPPINE_BANKS.find(b => b.code.toUpperCase() === code.toUpperCase());
  return found || {
    code: code.toUpperCase(),
    name: code,
    shortName: code,
    category: 'commercial',
    primaryColor: '#6366F1',
    gradient: 'from-[#1E1B4B] via-[#312E81] to-[#4F46E5]',
    textColor: '#FFFFFF',
    iconBg: '#0F0E26',
    logoEmoji: '💳',
    tagline: 'Custom Account',
  };
};
